POST https://strapi3333.herokuapp.com/api/auth/local
Content-Type: application/json

{
  "identifier": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

POST https://strapi3333.herokuapp.com/api/auth/local/register
Content-Type: application/json

{
  "username": "JeanBon",
  "firstname": "Jean",
  "lastname": "Bon",
  "email": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

POST https://strapi3333.herokuapp.com//api/announces
Content-Type: application/json

{

  "identifier": "jean.bon@gmail.com",
  "password": "bonjour123"
}



GET https://strapi3333.herokuapp.com/api/carpools
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImlhdCI6MTY0OTY2NzczNywiZXhwIjoxNjUyMjU5NzM3fQ.IJwjUgj0Y4rvupQC8I14jmJ_qUGcePkTVOUE7GZumhQ