POST https://strapi3333.herokuapp.com/api/auth/local
Content-Type: application/json

{
  "identifier": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

POST https://strapi3333.herokuapp.com/api/auth/local/register
Content-Type: application/json

{
  "username": "JeanBon",
  "firstname": "Jean",
  "lastname": "Bon",
  "email": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

GET https://strapi3333.herokuapp.com/api/announces?populate=activity&filters[type][$contains]=sport
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImlhdCI6MTY0OTY4MzU3MCwiZXhwIjoxNjUyMjc1NTcwfQ._PXBWkNO-J9f3vq_T8YJ7554Xdy_ezoMfg3tlsEl4ek

###

GET https://strapi3333.herokuapp.com/api/announces?populate=announces&filters[type][id][$gt]=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImlhdCI6MTY0OTY4MzU3MCwiZXhwIjoxNjUyMjc1NTcwfQ._PXBWkNO-J9f3vq_T8YJ7554Xdy_ezoMfg3tlsEl4ek

###
GET https://strapi3333.herokuapp.com/api/announces?populate=*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImlhdCI6MTY0OTY4MzU3MCwiZXhwIjoxNjUyMjc1NTcwfQ._PXBWkNO-J9f3vq_T8YJ7554Xdy_ezoMfg3tlsEl4ek


###
GET https://strapi3333.herokuapp.com/api/carpools?filters[$or][0][${element}][$eq]=${req.body[element]}&filters`;

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImlhdCI6MTY0OTY2NzczNywiZXhwIjoxNjUyMjU5NzM3fQ.IJwjUgj0Y4rvupQC8I14jmJ_qUGcePkTVOUE7GZumhQ

###
GET https://strapi3333.herokuapp.com/api/jobs?filters[$or][0][${element}][$eq]=${req.body[element]}&filters

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImlhdCI6MTY0OTY2NzczNywiZXhwIjoxNjUyMjU5NzM3fQ.IJwjUgj0Y4rvupQC8I14jmJ_qUGcePkTVOUE7GZumhQ

###
GET https://strapi3333.herokuapp.com/api/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImlhdCI6MTY0OTY2NzczNywiZXhwIjoxNjUyMjU5NzM3fQ.IJwjUgj0Y4rvupQC8I14jmJ_qUGcePkTVOUE7GZumhQ

###
GET https://strapi3333.herokuapp.com/api/users/41
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImlhdCI6MTY0OTY2NzczNywiZXhwIjoxNjUyMjU5NzM3fQ.IJwjUgj0Y4rvupQC8I14jmJ_qUGcePkTVOUE7GZumhQ
