POST https://strapi3333.herokuapp.com/api/auth/local
Content-Type: application/json

{
  "identifier": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

POST https://strapi3333.herokuapp.com/api/auth/local/register
Content-Type: application/json

{
  "username": "JeanBon",
  "firstname": "Jean",
  "lastname": "Bon",
  "email": "jean.bon@gmail.com",
  "password": "bonjour123"
}

###

GET https://strapi3333.herokuapp.com/api/announces
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImlhdCI6MTY0OTY2ODU0MywiZXhwIjoxNjUyMjYwNTQzfQ.rNRBVJudLzddt-1WaV9yF6xage4so5QQquO5J68kpDE

### 

GET https://strapi3333.herokuapp.com/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImlhdCI6MTY0OTY2ODU0MywiZXhwIjoxNjUyMjYwNTQzfQ.rNRBVJudLzddt-1WaV9yF6xage4so5QQquO5J68kpDE

